[vidara]
ftp = "ftp://vidara.io/upload"
upload = "https://vidara.io/upload"

  [[vidara.credentoial]]
  type = "ftp"
  user = "ghgfh"
  pass = "hgfhfgh"

  [[vidara.credentoial]]
  type = "upload"
  api_key = ""

[streamtape]
ftp = "ftp://streamtape.com/upload"
upload = "https://streamtape.com/upload"

  [[streamtape.credentoial]]
  type = "ftp"
  user = "hgffgh"
  pass = ""

  [[streamtape.credentoial]]
  type = "upload"
  api_key = "fhfgh"
